---
name: link-checker

services:
  traefik:
    image: traefik:v2.11

    ports:
      - 80:80

    labels:
      - traefik.enable=true
      - traefik.constraint-label=public
      - traefik.http.routers.traefik-public-http.rule=Host(`traefik.link-checker.localhost`)
      - traefik.http.routers.traefik-public-http.entrypoints=http
      - traefik.http.routers.traefik-public-http.service=api@internal
      - traefik.http.services.traefik-public.loadbalancer.server.port=8000

      # GENERIC MIDDLEWARES
      - traefik.http.middlewares.gzip.compress=true
      - traefik.http.middlewares.gzip.compress.excludedcontenttypes=image/png, image/jpeg, font/woff2

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

    command:
      - --providers.docker
      - --providers.docker.constraints=Label(`traefik.constraint-label`, `public`)
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --accesslog
      - --log
      - --api

  backend:
    build:
      context: ./backend
      args:
        - PLONE_VERSION=${PLONE_VERSION}
    volumes:
      - vol-site-data:/data
    labels:
      - traefik.enable=true
      - traefik.constraint-label=public
      # Service
      - traefik.http.services.svc-backend.loadbalancer.server.port=8080

      # Middleware
      ## VHM points to /Plone
      - "traefik.http.middlewares.mw-backend-vhm-classic.addprefix.prefix=/VirtualHostBase/http/link-checker.localhost/Plone/VirtualHostRoot/"

      # Routers
      ## From incoming directly to backend
      - traefik.http.routers.rt-backend-api.rule=Host(`link-checker.localhost`)
      - traefik.http.routers.rt-backend-api.entrypoints=http
      - traefik.http.routers.rt-backend-api.service=svc-backend
      - traefik.http.routers.rt-backend-api.middlewares=gzip,mw-backend-vhm-classic

volumes:
  vol-site-data: {}